# Generated by Django 4.0.4 on 2022-05-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/media/images/portafolio'),
        ),
    ]
